export type RiskLevel = "고위험" | "주의" | "보통";

export const RESIDENTS_STORAGE_KEY = "grandfood_test_residents";

export type Resident = {
  id: string;
  isPrototype?: boolean;
  name: string;
  age: number;
  gender: "여" | "남";
  facilityCode?: string;
  address?: string;
  /** 기존 테스트 데이터 호환용 동 단위 주소 */
  dong: string;
  condition: string;
  lastResponse: string;
  lastResponseTone: "danger" | "warning" | "neutral";
  risk: RiskLevel;
  guardianName: string;
  guardianPhone: string;
  note: string;
};

export const RESIDENTS: Resident[] = [
  {
    id: "001",
    name: "박순자",
    age: 82,
    gender: "여",
    dong: "역삼1동",
    condition: "고혈압 · 당뇨",
    lastResponse: "3일 미응답",
    lastResponseTone: "danger",
    risk: "고위험",
    guardianName: "박지훈 (자녀)",
    guardianPhone: "010-2938-****",
    note: "6개월 체중 -3.4kg, 저영양 위험 신호로 단백질 강화 식단 전환됨.",
  },
  {
    id: "002",
    name: "김영호",
    age: 78,
    gender: "남",
    dong: "역삼1동",
    condition: "신장질환",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "김은주 (배우자)",
    guardianPhone: "010-4471-****",
    note: "최근 14일 섭취 안정적, 특이사항 없음.",
  },
  {
    id: "003",
    name: "이말순",
    age: 85,
    gender: "여",
    dong: "대치2동",
    condition: "연하곤란",
    lastResponse: "2일 소량",
    lastResponseTone: "warning",
    risk: "주의",
    guardianName: "이수연 (자녀)",
    guardianPhone: "010-9021-****",
    note: "저작·연하 상태 재평가 예정 (2026.03 방문 평가 기준).",
  },
  {
    id: "004",
    name: "정복순",
    age: 80,
    gender: "여",
    dong: "삼성1동",
    condition: "골다공증",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "정민아 (자녀)",
    guardianPhone: "010-5512-****",
    note: "특이사항 없음.",
  },
  {
    id: "005",
    name: "최금동",
    age: 76,
    gender: "남",
    dong: "논현2동",
    condition: "고혈압",
    lastResponse: "어제 소량",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "최영식 (자녀)",
    guardianPhone: "010-7788-****",
    note: "나트륨 제한식 유지 중.",
  },
  {
    id: "006",
    name: "한상옥",
    age: 88,
    gender: "여",
    dong: "청담동",
    condition: "치매 초기 · 당뇨",
    lastResponse: "4일 미응답",
    lastResponseTone: "danger",
    risk: "고위험",
    guardianName: "한지민 (손녀)",
    guardianPhone: "010-3345-****",
    note: "미응답 이상 신호로 방문 확인 배정 필요.",
  },
  {
    id: "007",
    name: "서말자",
    age: 79,
    gender: "여",
    dong: "역삼1동",
    condition: "고지혈증",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "서준혁 (자녀)",
    guardianPhone: "010-2201-****",
    note: "특이사항 없음.",
  },
  {
    id: "008",
    name: "윤태식",
    age: 91,
    gender: "남",
    dong: "대치2동",
    condition: "심부전 · 고혈압",
    lastResponse: "5일 미응답",
    lastResponseTone: "danger",
    risk: "고위험",
    guardianName: "윤서아 (손녀)",
    guardianPhone: "010-6612-****",
    note: "장기 미응답 — 오늘 중 안부 확인 필요.",
  },
  {
    id: "009",
    name: "강복례",
    age: 74,
    gender: "여",
    dong: "삼성1동",
    condition: "경계고혈압",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "강민호 (자녀)",
    guardianPhone: "010-8843-****",
    note: "특이사항 없음.",
  },
  {
    id: "010",
    name: "임정자",
    age: 83,
    gender: "여",
    dong: "논현2동",
    condition: "당뇨 · 신기능 저하",
    lastResponse: "2일 소량",
    lastResponseTone: "warning",
    risk: "주의",
    guardianName: "임동현 (자녀)",
    guardianPhone: "010-1129-****",
    note: "eGFR 저하 추이 관찰 중, 인·칼륨 제한식 적용.",
  },
  {
    id: "011",
    name: "오필녀",
    age: 87,
    gender: "여",
    dong: "청담동",
    condition: "골감소증",
    lastResponse: "어제 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "오지은 (자녀)",
    guardianPhone: "010-4432-****",
    note: "특이사항 없음.",
  },
  {
    id: "012",
    name: "배동수",
    age: 81,
    gender: "남",
    dong: "역삼1동",
    condition: "만성폐쇄성폐질환",
    lastResponse: "3일 소량",
    lastResponseTone: "warning",
    risk: "주의",
    guardianName: "배수민 (자녀)",
    guardianPhone: "010-7723-****",
    note: "호흡곤란으로 식사량 저하, 소량 다회식 권고.",
  },
  {
    id: "013",
    name: "홍말선",
    age: 77,
    gender: "여",
    dong: "대치2동",
    condition: "고혈압",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "홍성민 (자녀)",
    guardianPhone: "010-3391-****",
    note: "특이사항 없음.",
  },
  {
    id: "014",
    name: "장옥희",
    age: 89,
    gender: "여",
    dong: "삼성1동",
    condition: "치매 · 고관절 수술 이력",
    lastResponse: "6일 미응답",
    lastResponseTone: "danger",
    risk: "고위험",
    guardianName: "장현우 (자녀)",
    guardianPhone: "010-9987-****",
    note: "6일 연속 미응답 — 긴급 확인 배정 대상.",
  },
  {
    id: "015",
    name: "조명자",
    age: 75,
    gender: "여",
    dong: "논현2동",
    condition: "당뇨 전단계",
    lastResponse: "오늘 완식",
    lastResponseTone: "neutral",
    risk: "보통",
    guardianName: "조은비 (자녀)",
    guardianPhone: "010-5560-****",
    note: "특이사항 없음.",
  },
  {
    id: "016",
    name: "남재춘",
    age: 84,
    gender: "남",
    dong: "청담동",
    condition: "고혈압 · 통풍",
    lastResponse: "2일 소량",
    lastResponseTone: "warning",
    risk: "주의",
    guardianName: "남지훈 (자녀)",
    guardianPhone: "010-2218-****",
    note: "퓨린 제한식 적용 중, 잔반량 증가 추이 관찰 필요.",
  },
];
